#!/usr/bin/env bash

# Mattermost Slack Emoji Transfer Tool

# Copyright (c) 2023 Maxwell Power
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom
# the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
# AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

if [ -z ${SLACK_TOKEN+x} ]; then echo "SLACK_TOKEN Missing" && exit 1; fi
if [ -z ${MM_URL+x} ]; then echo "MM_URL Missing" && exit 1; fi
if [ -z ${MM_LOGIN_ID+x} ]; then echo "MM_LOGIN_ID Missing" && exit 1; fi
if [ -z ${MM_PASSWORD+x} ]; then echo "MM_PASSWORD Missing" && exit 1; fi

##################################

function _usage() {
  printf "Usage: get \n"
  exit 0
}

function _getEmojiesList() {
  echo "Getting Emoji List ..."
  curl -O -s --header "Authorization: Bearer $SLACK_TOKEN" "https://slack.com/api/emoji.list"
  ls
}

function _downloadEmojies() {
  echo "Downloading Emojis from Slack ..."
  download
  echo "Clean System Emoji's before Upload"
  cleanSystemEmoji
}

function _createEmojies() {
  echo "Uploading Emojis to Mattermost ..."
  echo "This might take a while, and there is no progress bar"
  echo "You can watch the emoji selection dialogue in Mattermost to see if they are uploading"
  echo "Please wait ..."
  mmemoji create -o json -n *.{gif,jpg,png}
  echo "Done Uploading Emojis to Mattermost"
  echo "Check your Mattermost install to ensure they have copied successfully"
  echo "An API error above may not indicate upload failure and may be ignored"
}

if [ "$1" == 'run' ]; then
  echo "Getting Emojies from Slack and Uploading to Mattermost"
  _getEmojiesList
  _downloadEmojies
  _createEmojies
else
  _usage
fi
